[[redirects]]
  from = "/api/*"
  to = "https://frontend.test.mwanga.ng/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
